### ISSUE TITLE
4th order koch snowflake

### ISSUE THREAD

**Issue by r-a-v-a-s** [lithander/GroveScript#1]
If I change repeat to 4 in the koch snowflake example, then the six fold rotational symmetry is lost.

![broken_koch](https://cloud.githubusercontent.com/assets/12013378/12693972/a7bba66c-c6d1-11e5-84e1-f3726527af4a.png)

Am I misunderstanding how to change the order? Or is this a bug?

**Comment by lithander** [comment]
The symmetry isn't lost. But as you increase the repeat count the snowflake increases in size. And while _'repeat 3'_ fits the screen perfectly a _'repeat 4'_ snowflake is clipped by the screen boundaries. If you change "move 1" to "move 0.1" then even a  snoflake generated by applying the production rule 5 times (e.g. _'repeat 5'_) will be small enough to fit the screen.

**Comment by r-a-v-a-s** [comment]
Ah... Thanks a lot!
